\clearpage

# Introduction

Yelloweye Rockfish (*Sebastes ruberrimus*) are found from the Gulf of Alaska to northern Baja California in Mexico across the northeastern Pacific Ocean [@hart_pacific_1973;@love_rockfishes_2002]. Their core distribution is from southeast Alaska to central California on the west coast of the United States [@love_rockfishes_2002]. Yelloweye Rockfish in Puget Sound are considered isolated from the coastal waters population [@stewart_status_2009] and have been listed as threatened under the Endangered Species Act since 2010 [@drake_status_2010]. 

Yelloweye Rockfish are strongly associated with rocky bottom habitat, particularly areas of high relief [@love_rockfishes_2002], and adults are considered to be solitary and sedentary after settlement [@coombs_1979;@demott_1983]. However, new tagging studies suggest that adult Yelloweye Rockfish exhibit larger scale movement patterns more commonly than previously considered [@hannah_movement_2011;@rasmuson_movement_2025]. 

There has been little advancement on information pertaining to the stock structure of Yelloweye Rockfish since the previous benchmark assessment. As noted in @gertseva_stock_2017, there is evidence of genetic differences between Canadian waters (Strait of Georgia) and West coast coastal populations of Yelloweye Rockfish, but no evidence of differentiation across coastal populations [@siegle_genetics_2013]. @gao_isotope_2010 found that there was complete mixing of offspring from Oregon and Washington waters using otolith isotope analyses, indicating a single spawning stock in this portion of the Yelloweye Rockfish stock. Given the general perception of the sedentary nature of Yelloweye Rockfish adults and the moderate amount of mixing that occurs during the pelagic larval stage, the previous Yelloweye Rockfish assessment modeled the West coast population as a two-area assessment (California and a combined Oregon-Washington area) with a common stock recruitment relationship [@gertseva_stock_2017]. This update assessment maintains this basic structure.  

<!-- Scientific name, distribution, the basis for the choice of stock structure, including regional differences in life history or other biological characteristics that should form the basis of management units.  -->

## Life History

This section is not required for an update assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

## Ecosystem Considerations

This section is not required for an update assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

## Fishery Description

 This section is not required for an update assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

## Management History

Since the 2017 assessment, catch restrictions for Yelloweye Rockfish have continued, though as the stock recovers, the rebuilding plan has allowed for small catch increases that slightly loosened the constraining impact of this species.

This section is not required for an update assessment; please refer to the most recent full assessment [@gertseva_stock_2017] and @sec-mgmt for additional information.

## Management Performance{#sec-mgmt}

Yelloweye Rockfish removals have been substantially reduced since its designation as overfished in 2002 through a variety of management measures that eliminated retention in recreational fisheries, limited commercial retention, created broad spatial closures, and implemented new gear restrictions that reduced trawling in rocky habitats. Many of these restrictions remain in effect, though as Yelloweye Rockfish and other groundfish stocks have begun to rebuild, some management measures have been modified or removed in recent years. These include some additional allocations to recreational fisheries that remain constrained by Yelloweye Rockfish estimated discard mortality, the recent removal of the Yelloweye \gls{rca} for the trawl sector off of California and Oregon, and eliminating some gear restrictions in the RCAs for the non-trawl sector. 

Recent trends in total catch relative to management guidelines are available in @tbl-ye-management and show that total catch of Yelloweye Rockfish has remained below both the \gls{ofl} and \gls{acl} in each year since the previous assessment. Catch in @tbl-ye-management combines the two areas in this model as catch limits for Yelloweye Rockfish are managed as a single coast wide unit and includes both landings and estimated discard mortality. As in the previous assessment, total catches for each fleet in this update include both landings and estimated dead discard mortality. 

<!-- Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.  -->

## Fisheries off Canada and Alaska

This section is not required for an update assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.
