# Data

<!--- Provide temporal and spatial resolutions or sample size where appropriate for each of the subsections, below.--->

A summary of available data by type and fleet is available in @fig-data.

## Fishery-Dependent Data 

<!-- Commercial fisheries landings by state, year, and gear (PacFIN is the standard source for recent domestic commercial landings), historical catch estimates, discards, recreational fisheries catches, foreign removals; sample size information for length- and age-composition data by state, year and gear, including both the number of trips and fish sampled. Description of methods to estimate abundance indices, sample size information by survey and year. Include complete tables and figures and date of data extraction. -->

ADW - need to add a summary of FD data by fleet (one paragraph)

### Landings

A summary of total removals are provided in @tbl-all_removals and @fig-catch.

#### Commercial 

The time series of California historical commercial catches (1889-1980) of yelloweye rockfish remained unchanged from the 2017 assessment. Yelloweye rockfish landings estimates for 1981 through 2015 that were obtained by PacFIN and supplemented by WCGOP also remained unchanged.
Estimates of landings of yelloweye rockfish up to 2016 were unchanged from the previous assessment. Recent landings (2017-2024) were obtained from **PacFIN (www.pacfin.com)**. Landings data were extracted by gear type and state on and then combined into the area-specific fishing fleets used in the assessment. For the period from 2002 forward, when catch limits and area closures were implemented, year-specific PacFIN landings were supplemented with the discard amounts of yelloweye rockfish estimated by the WCGOP. The proportion of observed area-specific fleet discards in WCGOP were calculated and used to identify total fleet-specific discards from the GEMM. Estimated total discard amount of yelloweye rockfish were combined with year-specific PacFIN Landings to obtain the total catch of yelloweye rockfish within commercial fleets.

Historical commercial landings for yelloweye rockfish in Oregon were unchanged from the previous 2017 assessment. These include a comprehensive commercial catch reconstruction (1892-1986; **Karnowski et al. 2014**) and a reconstruction of the URCK/POP categories in PacFIN (ODFW 2017) that supplements PacFIN landings during 1987 through 1999. A small amount of historical yelloweye removals caught in Oregon waters but landed in California were provided by SWFSC (John Field, pers. comm.). These were included in the assessment by calculating the proportion of Oregon trawl catch and Oregon non trawl catch out of the total Oregon commercial catch and applying those proportions to the removals caught in Oregon but landed in California. 

PacFIN landings were rolled over from 1987 through 2016 and updated from 2017 through 2024. As the case with California, for the period from 2016 through 2023, updated WCGOP discard estimates were added to PacFIN landings by calculating the proportion of observed area-specific fleet WCGOP discards expanded from the fleet-specific GEMM total recorded discards to obtain the total catch of yelloweye rockfish within commercial fleets. 

For this assessment, historical commercial catches (1889-1980) of yelloweye rockfish in Washington were provided by Washington Department of Fish and Wildlife (WDFW), based on the historical reconstruction of rockfish landings in Washington (Theresa Tsou, and Fabio Caltabellotta pers. comm.). Commercial landings from 1981 through 2016 provided by WDFW in the last assessment and were used in this assessment. 

Recent commercial landings (2017-2024) were obtained from PacFIN. As the case with California and Oregon, landings were supplemented with the discard amount estimated by WCGOP using the proportion of observed discards multiplied by the total discards recorded by the GEMM, to obtain the total catch of yelloweye rockfish within commercial fleets.

#### Recreational 

A time series of historical California recreational catches of yelloweye rockfish (1928-1979) were also reconstructed by the NMFS’s SWFSC **(Ralston et al. 2010)** for the 2017 assessment, and these remained unchanged for this assessment. Removal data from 1980 to 2016 were carried over from the previous assessment and updated to include data from years 2017 through 2024 obtained from the **RecFIN database (www.recfin.com)**. Differential mortality rates according to depth of capture were accounted for in these estimates, where depth-specific release information was available. 

Updated historical recreational removals from 1979 through 2000 were provided by ODFW (**Whitman 2024**). Removals from 1973 - 1978 were rolled over from the 2017 assessment. Recreational removals from RecFIN were updated from 2017 - 2024 and rolled over from 2001 - 2016. RecFIN removals include an estimate of discard mortality and represent total estimated removals. 

For the 2017 assessment, recreational removals for the period between 1975 and 2016 were provided by WDFW (Theresa Tsou, per. comm.), mortality by depth estimates for yelloweye rockfish were provided by the PFMC Groundfish Management Team (Lynn Mattes, pers. comm.), and the removals were adjusted accordingly, where depth-specific release information was available. Differential mortality rates according to depth of capture are now accounted for in these estimates in the RecFIN database from 2005 through 2024. Since the RecFIN removal data from 2005 through 2016 were very similar to the estimates in the previous assessment, removals during this time period were unchanged and updated with data from 2017 through 2024 from RecFIN.

#### Bycatch in the Foreign POP Fishery

Bycatch in the foreign POP fishery was unchanged from the previous assessment and included in the trawl fleets for California and Oregon/Washington. Please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

**ADW - Sam, please review the above. **

#### Bycatch in the At-Sea Pacific Hake Fishery

Bycatch for the At-Sea Pacific Hake fleet (ASHOP) was updated from 2017 through 2024 and included in the trawl fleets for California and Oregon/Washington. 

**ADW - Sam, please review the above. **

### Discards

** ADW - who was in charge of WCGOP data? I couldn't a write-up for this section. 
** MAJ - pretty sure this is also Sam **

### Fishery-Dependent Length and Age Compositions 

Most biological data for yelloweye rockfish were reported for both sexes combined. Since composition data and estimates of growth parameters for yelloweye rockfish did not indicate sexual dimorphism, frequency distributions were generated by year for females and males combined. Sampling statistics (number of samples and number of individual fish) for each fleet and year were used to create length and frequency distributions, and are shown from **Table X** through **Table X**. 

**Note- these tables will show N trips and N fish for each fleet **

Length composition data from commercial and recreational fisheries were compiled into 2-cm increment length bins, ranging from 10 to 74 cm. Most lengths were reported as fork lengths, but there were some in the recreational fisheries that were reported as total lengths. A sample of **several hundreds of fish** for which both fork and total lengths were taken were analyzed and a linear relationship (R2 = 0.999) was developed to convert total to fork length. 

Due to sparse sampling as a result of regulatory discard requirements, raw length frequencies are calculated as the count of fish within a given size bin. **This has been the case in previous assessments, and preliminary investigation of alternate weighting procedures revealed little sensitivity to this choice**.

The initial input sample sizes for length frequency distributions of yelloweye rockfish fishery-dependent sources were calculated by year as a function of the number of trips (or samples in the case of recreational fleets) and number of fish sampled, following **Stewart and Hamel (2014)**:
 **ADD FUNCTIONS**

This method was developed based on analysis of the input and model-derived effective sample sizes from West Coast groundfish stock assessments. A step-wise linear regression was used to estimate the increase in effective sample size per sample based on fish-per-sample and the maximum effective sample size for large numbers of individual fish.
 
Age composition data from fisheries ranged from age 0 to age 65. Age composition data were compiled as conditional ages at length (CAAL) distributions by fleet and year. The CAAL approach uses an age-length matrix, in which columns correspond to ages and rows to length bins. The distribution of ages in each column then is treated as a separate observation, conditioned on the corresponding length bin (row). The conditional ages-at-length approach has been used in most stock assessments on the West Coast of the United States in the last decade, since it has several advantages over the use of marginal age frequency distributions. Age structures are usually collected from the individuals that have been measured for length. If the standard age compositions are used along with length frequency distributions in the assessment, the information on year class strength may be double-counted since the same fish are contributing to likelihood components that are assumed to be independent. The use of conditional age distributions within each length bin allows avoiding such double-counting. Also, the use of conditional ages at length distributions allows the reliable estimation of growth parameters within the assessment model. The initial sample sizes for conditional ages-at-length data were the actual numbers of fish on which each composition is based.
Biological information was obtained from a variety of sources. These sources are described below by state and fleet. The length compositions constructed from these data are shown in **Figure X** through **Figure X**. The age compositions constructed from these data are shown in **Figure X** through **Figure X**. 

#### California 

Updated length composition data for California commercial catches (trawl and non-trawl) were available from PacFIN (extracted on April 4, 2025). Trawl length data were collected between 1978 and 2024, while non-trawl length data were available between 1979 and 2002. Trawl length data were also available from WCGOP between 2019 and 2022, while non-trawl length data were available for the period between 2004 and 2023. Updated length composition data for California recreational fishery were obtained from RecFIN (**extracted …**). These data yielded a relatively consistent number of samples between 1980 and 2024. In early periods (prior to 1993), the lengths from recreational fishery were measured as total length (and converted to fork length), and after 1993 as fork length. Updated length compositions from the California On-Board CPFV Observer Sampling Program were available for the years 1987-1999 and 2004-2024. 

Age composition data were extremely limited for California fisheries. No yelloweye rockfish age data were available from the Californian trawl fishery. A sample of only six fish was available from the non-trawl fishery for 2005 from the WCGOP and a limited amount of ages (52 fish) was provided by CDFW for the period 1978-1988 (John Budrick, pers. comm.). A limited amount of recently generated age data were provided from recreational fishery by the SWFSC for 1979-1984 (Don Pearson and John Field, pers. comm.) and by the CDFW for years 2009- 2016 (John Budrick, pers. comm.). The latter data set was generated from confiscated yelloweye rockfish collected from recreational catches, when retention for yelloweye rockfish was prohibited. 

#### Oregon 

Updated length composition data for Oregon trawl and non-trawl commercial fisheries were obtained from PacFIN (extracted on April 4, 2025). Trawl length compositions were available for years 1995-2024 and non-trawl length compositions were available for years 1995-2024. The WCGOP also provided length composition data for 2005-2023 from the trawl fishery and between 2004 and 2023 from the non-trawl fleet. Updated lengths from the recreational fishery were obtained from RecFIN for 1980-2024. These data were collected in the MRFSS and, the Ocean Recreational Boat Survey (ORBS) dockside sampling programs (total lengths were converted to fork lengths when needed), and from the Ocean Recreational Fishery Survey (ORFS, previously the Oregon onboard recreational observer program), which measures fish discarded at sea.

Updated age composition data from Oregon commercial fisheries were obtained from PacFIN and included samples from the trawl fishery (1141 fish) collected in 2001-2024 and from the non-trawl fishery (111 fish) for 2008-2024. The WCGOP also had samples for Oregon-Washington states (information not available at the state level) from trawl fisheries collected in 2004-2006 (77 fish) and from the non-trawl fisheries for 2004-2007 (79 fish). Age composition data from Oregon recreational fisheries were obtained from WDFW (who read age structures) for selected years between 1979 and 2012. Early samples from this dataset (in the 1970s and 1980s) were taken by an ODFW biologist in Garibaldi who saw the offshore fishery starting to develop. A limited amount of yelloweye rockfish age data from the recreational fishery, collected between 2009 and 2016 from fish that were illegally landed and confiscated (since no retention is allowed) were provided by ODFW.

#### Washington

Updated length composition data for the Washington trawl and non-trawl commercial fisheries were obtained from PacFIN (extracted on April 4, 2025). Trawl length compositions were available for 1996-2023 and non-trawl for 1980-2024. The WCGOP also provided lengths for 2005-2019 from the trawl fishery and for 2004-2023 from the commercial non-trawl fleet. Yelloweye rockfish lengths from the recreational fishery were obtained from RecFIN for 1981-2024.

Age composition data from Washington commercial fisheries were obtained from PacFIN and included samples from the trawl fishery (268 fish) collected between 2002 and 2023 and from the non-trawl fishery (2166 fish) collected between 2001 and 2024. The WCGOP also had samples for Oregon-Washington states (information not available at the state level) from trawl fisheries collected in 2004-2006 (77 fish) and from the non-trawl fisheries for 2004-2007 (79 fish). Ages from recreational fisheries were obtained from WDFW for selected years between 1979 and 2024. These data were collected in the MRFSS and in the WDFW Ocean Sampling Program (OSP) and obtained from RecFIN.

### Indices of Abundance

ADW - add a summary paragraph describing the FD indices.

#### California MRFSS Dockside CPUE, 1980-1999

This index was unchanged from the previous assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

#### California Onboard Observer CPUE, 1988-1998

The CDFW conducted an onboard CPFV sampling program in central California from 1987- 1998. This program sought to collect information on the recreational groundfish sector by recording catch, effort and length data at the level of a fishing trip. Subsequent work digitized the original data sheets and aggregated the relevant location information (time and number of observed anglers) to match the available catch information (**Monk et al. 2016**). 

Filtering of the data was done as follows:

•	removed trips with missing information,
•	removed drifts that were under 2 minutes (indicative of a non-standard drift),
•	removed year 1987 (under sampled),
•	removed reefs with <12 positive records or all positives in one year,
•	removed depths <30m and >160m, depths at which yelloweye were rarely or never encountered,
•	and removed county 85 (no positives).

This filtering improved the percent positive yelloweye from 10% to 14%, but also pinpointed trips with higher probabilities that yelloweye rockfish could be encountered by reducing total trips by almost half (**Table X**). Model selection explored the inclusion of MONTH, DEPTH, COUNTY, and REEF as factors, in addition to YEAR. The final model was YEAR+MONTH+DEPTH+COUNTY (**Table X**). The data generally met the assumptions of the GLM (**Figure X** and **Figure X**). Both bootstrapping and jackknifing estimates of uncertainty were calculated; jackknifing was used for the reference model (**Table X**). The delta-GLM model results were very different from the geometric average of the catch rates; uncertainty was at moderate levels (**Table X** and **Figure X**). The CPFV index show a similar population decline as the dockside index, with the CPFV index having lower levels of uncertainty (**Figure X**).

#### Oregon Onboard Observer CPUE, 2001 – 2024

The Oregon Onboard Observer (now Ocean Recreational Fisheries Survey, or ORFS) index was updated from the previous yelloweye rockfish assessment and updated drift-level catch-per-unit-effort data was obtained from ODFW through the end of 2024. The database contains information on catch by species (number of retained and released fish), effort (angler hours), sample depth, and bag limits and other relevant regulations (@monk_documentation_2013).  

The unfiltered data set contained 18,410 drifts. Multiple standardized filters are applied to remove outliers and data unsuitable for an index. These filters are very similar to filters applied in 2017 and include drifts without data needed for CPUE information, long drifts (below 95th quantile), drifts in deeper waters (less than 64fm, 99th quantile), drifts that were targeting primarily mid-water species, and drifts outside of the legal fishing depth (with a five fm buffer). Additionally, years with extreme low sample sizes (<10) were excluded, including 2003, 2016 and 2019. Finally, drifts onboard charters from Port Orford were removed due to small sample size. The final filtered dataset included 6,839 trips with a 6.1% encounter rate for yelloweye rockfish. 

Covariates evaluated included year, month, port, the open depths to fishing (all depths or inside 20/30/40fm), and a 5fm-binned depth of drift covariate. This is in contrast to the 2017 index, which was only able to evaluate a year covariate. The covariates listed above are standard to evaluate for this index in other assessments. Negative binomial models were fit using sdmTMB (version 0.6.0) to the drift-level data (catch with a log offset for adjusted angler hours). A model without the open fishing depths or month was selected as the best fit model by AIC (Table “model selection”). Acceptable diagnostics for the model were achieved (FIGURE – qqplot). The index of abundance in shown in Figure XXX and Table XXXX. A comparison to the ORFS index used in the previous assessment indicates that despite the change in modeling approach and the covariates included, most years overlap between the two indices and similar trends are observed (Figure “ORFS index comparison”). The updated index has reduced within-year variance and a lack of extreme swings in the standardized index value (e.g. 2013).

#### Oregon MRFSS Dockside CPUE, 1982-1999

This index was unchanged from the previous assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

#### Oregon ORBS Dockside (release only) CPUE, 2004-2024

The Ocean Recreational Boat Survey (ORBS) dockside index for Oregon was updated for this assessment. CPUE, expressed in terms of fish per angler-hour, was calculated by multiplying the number of anglers and the total trip time, minus the boat type-specific travel time. The database contains information on released fish by species (number of angler-reported released fish), effort (angler hours), sample location (port where data were collected), date, bag limits and other relevant regulations, boat type (charter or private), and trip type (e.g., bottom associated fish). 

The unfiltered data set contained 504,128 trips from 2001 - 2024. Since the previous yelloweye assessment, multiple data filters have been standardized, which are very similar to the 2017 assessment, and are applied to ORBS trip-level data to remove outliers and data unsuitable for an index. For this index, the time period was restricted to years when retention of yelloweye rockfish was prohibited, which began on January 1, 2004. There were two differences in the filtering in this updated index. One, the previous index began in 2005, which was determined to be an error in the timing of the implementation of prohibited status for yelloweye. Given that prohibition was in effect on January 1, the year 2004 is included in this updated index. The second difference in filtering is the elimination of the Stephens-MacCall filter in the updated index. This filter has not been used for several assessment cycles, based on a recommendation from NWFSC staff (pers. comm. A. Whitman, ODFW). The final dataset included 133,039 trips (TABLE “percent_pos.csv”) from 2004 – 2024 with an overall encounter rate of 7.4%.

Covariates evaluated included year, month, port, the open depths to fishing (all depths or inside 20/30/40 fm), and boat type. These are the same covariates evaluated in the 2017 ORBS index, apart from the open depths of the fishery. The final model in 2017 included boat type, port and year. Negative binomial models were fit in sdmTMB (Version 0.6.0) to the trip-level data (catch with a log offset for adjusted angler hours). The final model selected includes year, month, port, boat type and open fishery depths, which was the best fit model by AIC in this series (TABLE “model_selection.csv”). Acceptable diagnostics for the model were achieved (FIGURE – qqplot). The index of abundance in shown in Figure XXX and Table XXXX. ODFW no longer maintains the deltaGLM code that was used to develop the 2017 index and so the index was updated to use the currently accepted modeling approach for PFMC groundfish assessments (sdmTMB). To bridge this change, the 2017 model index structure was applied to the current dataset using sdmTMB and compared to the deltaGLM index used in the 2017 assessment and the current recommended updated index in Figure XX (“ORBS index comparison”). There are some differences observed in 2005 – 2009 between the deltaGLM index and the two sdmTMB indices; however, this appears to be largely driven by the updated modeling approach. A comparison to the ORFS index used in the previous assessment indicates that despite the change in modeling approach and the covariates included, most years overlap between the two indices and similar trends are observed (Figure “ORFS index comparison”). The updated index has reduced within-year variance and a lack of extreme swings in the standardized index value (e.g. 2013). 

#### Washington Dockside CPUE, 1982-2001

This index was unchanged from the previous assessment; please refer to the most recent full assessment [@gertseva_stock_2017] for additional information.

## Fishery-Independent Data

ADW - add summary paragraph of FI data. 

### Triennial Bottom Trawl Survey

** Claire updated these - write-up?**

### West Coast Bottom Trawl Survey 

** Claire updated these - write-up?**

### IPHC Setline Survey

The IPHC has conducted an annual longline survey for Pacific halibut off the coast of Oregon and Washington (IPHC area “2A”) since 1997 (no surveys were performed in 1998 or 2000). Beginning in 1999, this has been a fixed station design, with roughly 1,800 hooks deployed at each of 84 locations. Before 1999, station locations were not fixed, and, therefore, those years are not used in the index. Rockfish bycatch, mainly yelloweye, was recorded during this survey, although values for 1999 and 2001 are estimates based on subsampling the first 20 hooks of each 100-hook skate. The gear used to conduct this survey, while designed specifically to efficiently sample Pacific halibut, is similar to that used in some earlier line fisheries that targeted adult yelloweye rockfish. Some variability in exact sampling location is unavoidable, and leeway is given in the IPHC methods to center the set on the target coordinates but to allow wind and currents to dictate the actual direction in which the gear is deployed. This can result in different habitats accessed at each fixed location among years. The number of skates used can also differ somewhat from year to year; skates hauled (i.e., 100 hooks/skate) is thus used as the unit of effort for all years. This has been the standard effort used in past yelloweye rockfish stock assessments. 

New to this assessment is the consideration of eight additional survey stations conducted by WDFW (2007-2016). These stations are arranged around IPHC station 1082 (one of the more notable stations to encounter yelloweye rockfish) and are conducted during spring, summer, and fall months. Only summer months were considered here in order to match the time of year 37 sampled by the IPHC survey. Survey sets at the WDFW stations used 3 skates with 100 hooks each, a departure from that used by the IPHC survey. Like the IPHC survey, effort was standardized as 100 hooks/skate. These stations were added to the IPHC stations when calculating the index of abundance. The full survey used in this assessment combined all stations in Oregon and Washington, fitting the area of the stock, instead of using state-specific indices. Data were filtered first to remove all depths with no or few encounters, then we removed stations that also rarely encountered yelloweye (average less than encounter a year). This left 11 stations for analysis. Both filtering levels improved the percent positive from an initial 11% to 80%. 

A log-normal generalized linear model with a log link in the “sdmTMB” R package was used to standardize the CPUE. Model selection using the Akaike Information Criteria for small samples (AICc) was conducted to select which variables were included in the model. The final model included year, station, and depth as explanatory variables. Diagnostic tools to ensure the model fit was satisfactory included checking whether the hessian matrix is positive definite, the presence of extreme eigenvalues, and if the non-linear minimizer suggests convergence. These diagnostics were conducted with the “sanity( )” function in the sdmTMB package. Lastly, the index was centered at zero to facilitate comparisons with the index used for the 2017 assessment.

### Fishery-Independent Length and Age Compositions

Length composition data were available for all three fishery-independent surveys. The length composition data from the previous assessment was used up to 2016. Data from 2017 through 2024 was obtained for NWFSC West Coast Groundfish Bottom Trawl Survey and the Triennial survey were obtained using functions from the **{nwfscSurvey} R package**. The IPHC survey data was provided from WDFW. 
A summary of sampling efforts (number of hauls and number of individual fish) in all surveys is provided in **Table X** and **Table X**. Length composition data were compiled into 33 length bins, ranging from 10 to 74 cm. Year-specific length frequency distributions generated for each survey are shown in **Figure X**.

The initial input sample sizes for the survey length frequency distribution data were calculated as a function of both the number of fish and number of tows (or STLKEY in the case of the IPHC survey) sampled using the method developed by via Stewart’s Method from the **Pacific Ocean Perch assessment**:

**ADD FUNCTIONS**

which precedes the **Stewart and Hamel (2014)** method that is more specific to species types.

Age composition data were available from the NWFSC trawl survey and IPHC surveys through the same sources as the length data. No age data were available from the triennial survey. As in the case of fishery data, age composition data were assembled into 66 age bins, ranging from age 0 to age 65. Year-specific age frequency distributions generated for each survey are shown in **Figure X** and **Figure X**. In the model, age composition data from the surveys were compiled as conditional distributions of ages at length by survey and year. The initial sample sizes for conditional age-at-length data were the actual numbers of fish on which each composition is based.

## Biological Parameters and Data

ADW - need summary statement for bio parms. 

### Natural Mortality 

The approach to natural mortality was unchanged from the previous assessment (@gertseva_stock_2017). M is fixed at 0.0439. 

ADW - do we need more than this? 

### Maturity 

The approach to maturity was unchanged from the previous assessment (@gertseva_stock_2017).

### Fecundity 

The approach to fecundity was unchanged from the previous assessment (@gertseva_stock_2017).

### Length-Weight Relationship 

The length-weight relationship used in this assessment is based on data collected in the NWFSC trawl survey obtained from the **{nwfscSurvey} R package**. Length-weight curves were fitted with the sexes combined using the following relationship:

**ADDE FUCNTION**

Where W is individual weight (kg), L is total natural length (cm) and ⍺ and  β are coefficients used as constants.

The parameters derived from this analysis were as follows: ⍺ = 7.183309·10-6, and β  = 3.244801 (**Figure X **(can be found under Rcode > model_params > plots)). We updated parameters used in the 2011 assessment, since many samples used were based on total lengths in addition to those based on fork lengths.

### Ageing Error

** Morgan was going to write up **

## Environmental and Ecosystem Data 

As with the previous assessment (@gertseva_stock_2017), there are no environmental or ecosystem data explicitly included in this update assessment due to the lack of information regarding environmental drivers of Yelloweye Rockfish population dynamics. 

## Data Considered but not Used in Assessment 

No new sources of data were considered in this update assessment. 

<!--- ADW - commented out all the old text below, moved new relevant text to above outline, re-wrote some sections.
2 Assessment
2.1 Data
**Data used in the yelloweye rockfish assessment are summarized in **Figure X**. These data include both fishery-dependent and fishery-independent sources. Types of data that inform the model include catch, length and age frequency data from seven commercial and recreational fishing fleets. Fishery-dependent biological data used in the assessment originated from both port-based and on-board observer sampling programs. Recreational observer data from Oregon and California were used to construct indices of relative abundance. Yelloweye rockfish catch in the International Pacific Halibut Commission’s (IPHC) long-line survey is also included in an index of relative abundance for Washington and Oregon; IPHC length and age frequency data are also used. Relative biomass indices and information from biological sampling from trawl surveys were included as well; these trawl surveys were conducted by the Northwest Fisheries Science Center and the Alaska Fisheries Science Center of the National Marine Fisheries Service (NMFS).**
2.1.1 Fishery removals
**The fishery removals in the assessment are divided among seven fleets operating within two areas: waters off California (area 1) and off Oregon and Washington (area 2). These fleets include California trawl, California non-trawl and California recreational fisheries, Oregon-Washington trawl and Oregon-Washington non-trawl, Oregon recreation and Washington recreational fleets. Trawl fisheries, in addition to domestic shoreside catches, include very small removals in the foreign Pacific ocean perch (POP) fishery and bycatch in the at-sea Pacific hake fishery. Landings in all seven fleets are shown in **Figure X** and detailed in **Table X**.**
**We reconstructed catches within each fleet by state. By necessity, they were estimated based on port of landing and not area of catch. The port of landing does not always coincide closely with the latitude at which fish were caught. This issue is particularly important for catches between Oregon and Washington. For instance, Oregon vessels, particularly those from northern ports such as Astoria/Warrenton, frequently fish in waters off Washington, but return to Oregon to land their catch. It is not possible to precisely convert port of landing into area of catch, especially for historical catches. The problem is even more challenging in regards to assigning lengths and age data collected by port samplers at the point of landings to area of catch. This issue has become more apparent in recent years, as larger, interagency catch reconstruction efforts have been made. At this point, no reliable method exists to estimate the portion of catches landed in Oregon but caught in Washington and vice versa, nor to do the same for biological data. Therefore, within the overall assessment area, Washington and Oregon were combined into one area, while California was treated as a separate area (in the previous assessment all three states were treated as separate areas).**
**As mentioned earlier, yelloweye rockfish have historically been a prized catch for both commercial and recreational fleets and have largely been retained when encountered. A historical trawl discard study **(Pikitch et al. 1988)** confirms that virtually 100% of yelloweye rockfish catch was retained. Therefore, for the period prior to 2002, it was assumed that all catch was retained and landed.**
**From 2002 forward, when catch limits and area closures were implemented and a portion of yelloweye catches were discarded, the total catch was estimated from both landings and dead discards. Discard information was obtained from the West Coast Groundfish Observer Program (WCGOP). The WCGOP was implemented in 2001 and began with gathering bycatch and discard information on board fishing vessels for the limited entry trawl and fixed gear fleets. Observer coverage has expanded to include the California halibut trawl, the nearshore fixed gear and pink shrimp trawl fisheries. Since 2011, the WCGOP provides 100% at-sea observer monitoring of catch for the catch share-based Individual Fishing Quotas (IFQ) fishery.**
2.1.1.1 Commercial and recreational removals
**Catches of yelloweye rockfish were reconstructed back to 1889, and the assessment assumes equilibrium unfished conditions of the stock prior to that. Recent commercial catch data (1981-2016) for stock assessments are available from the Pacific Fisheries Information Network (PacFIN), a regional fisheries database that manages fishery-dependent information in cooperation with NMFS) and West Coast state agencies. Recent recreational catch data were obtained either from state agencies or from the Recreational Fisheries Information Network (RecFIN), a regional source of recreational data managed by the Pacific States Marine Fisheries Commission (PSMFC).**
**Prior to 1981, however, catch information is sparse, and there is no database analogous to PacFIN to handle the data. Historically, landed catch of rockfish have been reported as mixed-species groups that have similar market value, rather than as individual species **(Barss and Niska 1978, Douglas 1998, Lynde 1986, Niska 1976, Tagart and Kimura 1982)**. These groups are called “market categories”. The species compositions of these mixed-species market categories have changed over time, with technological advances in fishing gear and development of different fisheries. Therefore, reconstruction of historical landings of rockfish has been a challenge.**
**However, in recent years, significant progress has been made by the state agencies and NMFS in reconstructing a comprehensive species-specific time series of catch for use in stock assessments. This assessment relies heavily on the results of these recent efforts. The sources used in the assessment to inform historical commercial and recreational landings within each West Coast state are described below.**
2.1.1.1.1 California
2.1.1.1.1.1 Commercial
The time series of California historical commercial catches (1889-1980) of yelloweye rockfish remained unchanged from the 2017 assessment. Yelloweye rockfish landings estimates for 1981 through 2015 that were obtained by PacFIN and supplemented by WCGOP also remained unchanged.
Estimates of landings of yelloweye rockfish up to 2016 were unchanged from the previous assessment. Recent landings (2017-2024) were obtained from **PacFIN (www.pacfin.com)**. Landings data were extracted by gear type and state on and then combined into the area-specific fishing fleets used in the assessment. For the period from 2002 forward, when catch limits and area closures were implemented, year-specific PacFIN landings were supplemented with the discard amounts of yelloweye rockfish estimated by the WCGOP. The proportion of observed area-specific fleet discards in WCGOP were calculated and used to identify total fleet-specific discards from the GEMM. Estimated total discard amount of yelloweye rockfish were combined with year-specific PacFIN Landings to obtain the total catch of yelloweye rockfish within commercial fleets.
2.1.1.1.1.2 Recreational
A time series of historical California recreational catches of yelloweye rockfish (1928-1979) were also reconstructed by the NMFS’s SWFSC **(Ralston et al. 2010)** for the 2017 assessment, and these remained unchanged for this assessment. Removal data from 1980 to 2016 were carried over from the previous assessment and updated to include data from years 2017 through 2024 obtained from the **RecFIN database (www.recfin.com)**. Differential mortality rates according to depth of capture were accounted for in these estimates, where depth-specific release information was available. 
2.1.1.1.2 Oregon
2.1.1.1.2.1 Commercial
Historical commercial landings for yelloweye rockfish in Oregon were unchanged from the previous 2017 assessment. These include a comprehensive commercial catch reconstruction (1892-1986; **Karnowski et al. 2014**) and a reconstruction of the URCK/POP categories in PacFIN (ODFW 2017) that supplements PacFIN landings during 1987 through 1999. A small amount of historical yelloweye removals caught in Oregon waters but landed in California were provided by SWFSC (John Field, pers. comm.). These were included in the assessment by calculating the proportion of Oregon trawl catch and Oregon non trawl catch out of the total Oregon commercial catch and applying those proportions to the removals caught in Oregon but landed in California. 
PacFIN landings were rolled over from 1987 through 2016 and updated from 2017 through 2024. As the case with California, for the period from 2016 through 2023, updated WCGOP discard estimates were added to PacFIN landings by calculating the proportion of observed area-specific fleet WCGOP discards expanded from the fleet-specific GEMM total recorded discards to obtain the total catch of yelloweye rockfish within commercial fleets. 
2.1.1.1.2.2 Recreational
Updated historical recreational removals from 1979 through 2000 were provided by ODFW (**Whitman 2024**). Removals from 1973 - 1978 were rolled over from the 2017 assessment. Recreational removals from RecFIN were updated from 2017 - 2024 and rolled over from 2001 - 2016. RecFIN removals include an estimate of discard mortality and represent total estimated removals. 
2.1.1.1.3 Washington
2.1.1.1.3.1 Commercial
For this assessment, historical commercial catches (1889-1980) of yelloweye rockfish in Washington were provided by Washington Department of Fish and Wildlife (WDFW), based on the historical reconstruction of rockfish landings in Washington (Theresa Tsou, and Fabio Caltabellotta pers. comm.). Commercial landings from 1981 through 2016 provided by WDFW in the last assessment and were used in this assessment. 
Recent commercial landings (2017-2024) were obtained from PacFIN. As the case with California and Oregon, landings were supplemented with the discard amount estimated by WCGOP using the proportion of observed discards multiplied by the total discards recorded by the GEMM, to obtain the total catch of yelloweye rockfish within commercial fleets.
2.1.1.1.3.2 Recreational
For the 2017 assessment, recreational removals for the period between 1975 and 2016 were provided by WDFW (Theresa Tsou, per. comm.), mortality by depth estimates for yelloweye rockfish were provided by the PFMC Groundfish Management Team (Lynn Mattes, pers. comm.), and the removals were adjusted accordingly, where depth-specific release information was available. Differential mortality rates according to depth of capture are now accounted for in these estimates in the RecFIN database from 2005 through 2024. Since the RecFIN removal data from 2005 through 2016 were very similar to the estimates in the previous assessment, removals during this time period were unchanged and updated with data from 2017 through 2024 from RecFIN.
2.1.1.1.4 Bycatch in the Foreign POP Fishery
**Between the mid-1960s and mid-1970s, a small amount of yelloweye rockfish (32 mt over 11 years) was caught by foreign trawl fleets from the former Soviet Union, Japan, Poland, Bulgaria, and East Germany, which targeted aggregations of Pacific ocean perch (POP) in the waters off the U.S. West Coast **(Love et al., 2002)**. **Rogers (2003)** estimated removals of POP and other species caught within this foreign POP fishery, including removals of yelloweye rockfish. In the assessment, we used estimates of yelloweye bycatch in the foreign POP fishery between 1966 and 1976 as estimated by **Rogers (2003)**.** 
2.1.1.1.5 Bycatch in the At-Sea Pacific Hake Fishery
**Small amounts of yelloweye rockfish catch have been reported for the Pacific hake fishery. That time series cover the period between 1976 and 2016 and include catches removed by foreign and domestic fisheries as well as those obtained during the time of Joint Ventures. The At-Sea Hake Observer Program (A-SHOP) monitors the at-sea hake processing vessels and collects total catch and bycatch data. The annual amounts of yelloweye rockfish bycatch in the at-sea hake fishery, collected by A-SHOP, were obtained from the North Pacific Database Program (NORPAC). The total amount caught in this fishery since 1976 is less than 11 mt.**
2.1.2 Abundance Indices
**Indices of abundance provide an indicator of population dynamics by tracking portions of the population through time. All indices currently available for yelloweye rockfish are treated as relative measures of abundance, as modified by index-specific selectivity, and none of the sampling provides an absolute measure of population size along the spatial extent of the current stock assessment.**
**This assessment utilizes fishery-independent data from three surveys, including two bottom trawl surveys and one hook-and-line survey. Bottom trawl surveys were conducted on the continental shelf and slope of the Northeast Pacific Ocean by the AFSC and NWFSC and include the AFSC shelf survey (often called “triennial”, since it was conducted every third year) and the NWFSC shelf-slope bottom trawl survey. Details on latitudinal and depth coverage of these surveys by year are presented in **Table X**. The hook-and-line survey was conducted by the IPHC.**
**The two bottom trawl surveys do not encounter yelloweye rockfish often (**Table X** and **Table X**), while the IPHC survey targets on halibut and encounters rockfish as bycatch. To supplement the lack of directed yelloweye rockfish surveys, this stock assessment also utilizes several fishery-dependent abundance indices that use catch-per-unit-effort (CPUE) as a relative measure of population abundance. Common to all of these fishery-dependent indices is the high frequencies of zero yelloweye rockfish catches. Thorough data filtering had to be done to identify trips in areas and habitats with the potential to encounter yelloweye rockfish.**
2.1.2.1 Fishery-Independent Indices
2.1.2.1.1 Bottom Trawl Surveys
2.1.2.1.1.1 AFSC Triennial Survey
**The AFSC triennial survey was conducted every third year between 1977 and 2004. In 2004 this survey was conducted by the NWFSC. Survey methods are most recently described in **Weinberg et al. (2002)**. The basic design was a series of equally spaced transects from which searches for tows in specific depth ranges were initiated. Over the years, the survey area varied in depth and latitudinal range (**Table X**). Prior to 1995, the depth range was limited to 366 m (200 fm) and the surveyed area included four INPFC areas (Monterey, Eureka, Columbia and U.S. Vancouver). After 1995, the depth coverage was expanded to 500 m (275 fm) and the latitudinal range included not only the four INPFC areas covered in the earlier years, but also part of the Conception area with a southern extent of 34o50’ N. latitude. For all years, except 1977, the shallower surveyed depth was 55 m (30 fm); in 1977 no tows were conducted shallower than 91 m (50 fm). No yelloweye were observed deeper that 366 meters; therefore, we used a single time series to construct an abundance index from this survey. The data from the 1977 survey were not used in the assessment, because of the differences in depths surveyed and the large number of “water hauls”, when the trawl footrope failed to maintain contact with the bottom **(Zimmermann et al., 2001)**. The tows conducted in Canadian and Mexican waters were also excluded.**
2.1.2.1.1.2 NWFSC West Coast Groundfish Bottom Trawl Survey
**The NWFSC trawl survey has been conducted annually since 2003, and the data between 2003 and 2016 were used in this assessment. The survey consistently covered depths between 55 and 1280 m (30 and 700 fm) and the latitudinal range between 32o34’ and 48o22’ N. latitude, the extent of all five INPFC areas on the U.S. West Coast (**Table X**). The survey is based on a random-grid design, and four industry chartered vessels per year are assigned an approximately equal number of randomly selected grid cells. The survey is conducted from late May to early October, and is divided into two passes, with two vessels operating during each pass. The survey methods are most recently described in detail in **Keller et al. (2017)**.**
2.1.2.1.1.3 Bottom trawl survey abundance indices
**Bottom trawl survey indices were calculated only for Oregon-Washington area, since neither survey had a sufficient number of yelloweye positive hauls in California waters (with some years having no positive hauls at all). Summaries of surveys sampling effort with total number of survey hauls along with yelloweye positive hauls by area are provided in **Table X** and **Table X**.**
**We analyze data from the triennial survey and NWFSC trawl survey using the Vector Autoregressive Spatial Temporal (VAST) delta-model (**Thorson et al. 2015**), implemented as an R package (Thorson and Barnett n.d.) and publicly available online (https://github.com/James-Thorson/VAST). We specifically include spatial and spatio-temporal variation in both encounter probability and positive catch rates, a logit-link for encounter probability, and a log-link for positive catch rates. We also include vessel-year effects for each unique combination of vessel and year in the database, to account for the random selection of commercial vessels used during sampling (**Helser et al. 2004**, **Thorson and Ward 2014**). We approximate spatial variation using 250 knots, and use the bias-correction algorithm (**Thorson and Kristensen 2016**) in Template Model Builder (**Kristensen et al. 2016**). Further details regarding model structure are available in the user manual (https://github.com/James-Thorson/VAST/blob/master/examples/VAST_user_manual.pdf). To confirm convergence of the model estimation algorithm, we confirm that the Hessian matrix is positive definite and that the absolute-value of the final gradient of the log-likelihood with respect to each fixed effect was <0.0001 for each fixed effect.
Following advice from the Scientific and Statistical Committee (SSC) of the Pacific Fishery Management Council (PFMC), we use the following three diagnostics for model fit:
1. The Quantile-Quantile (Q-Q) plot, generated by comparing each observed datum with its predicted distribution under the fitted model, calculating the quantile of that datum, and comparing the distribution of quantiles with its expectation under a null model (i.e., a uniform distribution). This Q-Q plot shows no evidence that the model fails to capture the shape of dispersion shown in the positive catch rate data (**Figure X** and **Figure X**).
2. A comparison of predicted and observed proportion encountered when binning observations by their predicted encounter probability. This comparison shows no evidence that encounter probabilities are over-estimated for low-encounter-probability observations, or vice versa. 
3. A visualization of Pearson residuals for encounter probability and positive catch rates associated with each knot. This comparison shows no evidence of residual spatial patterns for either model component (**Figure X** through **Figure X**). Estimated abundance indices for triennial and NWFSC trawl survey are shown in **Figure X** and **Figure X**, respectively. The triennial survey index shows an abrupt decline in 1992, and NWFSC trawl survey shows an increasing trend between 2004 and 2013 with lower estimates in the last two years. Comparison of VAST abundance indices used in the assessment with estimates calculated using the designed-based area swept approach are provided in **Figure X** and **Figure X**, for the AFSC triennial and NWFSC surveys, respectively. **Figure X** and **Figure X** show comparisons of VAST indices with abundance estimates used in 2011 assessment, calculated using a non-spatial delta-GLMM approach, for the AFSC triennial and NWFSC surveys respectively.**
2.1.2.1.2 IPHC Longline Survey
The IPHC has conducted an annual longline survey for Pacific halibut off the coast of Oregon and Washington (IPHC area “2A”) since 1997 (no surveys were performed in 1998 or 2000). Beginning in 1999, this has been a fixed station design, with roughly 1,800 hooks deployed at each of 84 locations. Before 1999, station locations were not fixed, and, therefore, those years are not used in the index. Rockfish bycatch, mainly yelloweye, was recorded during this survey, although values for 1999 and 2001 are estimates based on subsampling the first 20 hooks of each 100-hook skate. The gear used to conduct this survey, while designed specifically to efficiently sample Pacific halibut, is similar to that used in some earlier line fisheries that targeted adult yelloweye rockfish. Some variability in exact sampling location is unavoidable, and leeway is given in the IPHC methods to center the set on the target coordinates but to allow wind and currents to dictate the actual direction in which the gear is deployed. This can result in different habitats accessed at each fixed location among years. The number of skates used can also differ somewhat from year to year; skates hauled (i.e., 100 hooks/skate) is thus used as the unit of effort for all years. This has been the standard effort used in past yelloweye rockfish stock assessments. New to this assessment is the consideration of eight additional survey stations conducted by WDFW (2007-2016). These stations are arranged around IPHC station 1082 (one of the more notable stations to encounter yelloweye rockfish) and are conducted during spring, summer, and fall months. Only summer months were considered here in order to match the time of year 37 sampled by the IPHC survey. Survey sets at the WDFW stations used 3 skates with 100 hooks each, a departure from that used by the IPHC survey. Like the IPHC survey, effort was standardized as 100 hooks/skate. These stations were added to the IPHC stations when calculating the index of abundance. The full survey used in this assessment combined all stations in Oregon and Washington, fitting the area of the stock, instead of using state-specific indices. Data were filtered first to remove all depths with no or few encounters, then we removed stations that also rarely encountered yelloweye (average less than encounter a year). This left 11 stations for analysis. Both filtering levels improved the percent positive from an initial 11% to 80%. 
A log-normal generalized linear model with a log link in the “sdmTMB” R package was used to standardize the CPUE. Model selection using the Akaike Information Criteria for small samples (AICc) was conducted to select which variables were included in the model. The final model included year, station, and depth as explanatory variables. Diagnostic tools to ensure the model fit was satisfactory included checking whether the hessian matrix is positive definite, the presence of extreme eigenvalues, and if the non-linear minimizer suggests convergence. These diagnostics were conducted with the “sanity( )” function in the sdmTMB package. Lastly, the index was centered at zero to facilitate comparisons with the index used for the 2017 assessment.
2.1.2.2.1 California MRFSS Dockside CPUE, 1980-1999
**The California dockside sampling of the Commercial Passenger Fishing Vessel (CPFV) and private boat sectors was available from 1980-2003, but the years 1989-1991 were not sampled. Years after 1999 were also excluded due to catch restrictions, and thus changing catchability over a short time period. An attempt to correct for this management change was made by using management period as a factor in an exploratory model, but this proved unsuccessful, thus the time series was truncated at 1999. Further filtering of additional years, regions and subregions with little to no catch of yelloweye rockfish improved the positive catch rate of yelloweye from 4% to 16% (**Table X**). One additional filter, the Stephens-MacCall method (**Stephens and MacCall 2004**) was also applied. This approach uses a linear model to relate yelloweye rockfish catches to the catches of others species, thus inferring trips likely to catch yelloweye rockfish to the species composition of the catch. Applying this filter further increased the presence of yelloweye rockfish to 53%. The final model includes the factors YEAR and AREA (**Table X**). The data generally met the assumptions of the GLM (**Figure X** and **Figure X**) and jackknifing was used to estimate uncertainty (**Table X**). The index shows a general decline in yelloweye rockfish over the time period, with moderate to high levels of uncertainty (**Figure X**).**
2.1.2.2.2 California Onboard Observer CPUE, 1988-1998
The CDFW conducted an onboard CPFV sampling program in central California from 1987- 1998. This program sought to collect information on the recreational groundfish sector by recording catch, effort and length data at the level of a fishing trip. Subsequent work digitized the original data sheets and aggregated the relevant location information (time and number of observed anglers) to match the available catch information (**Monk et al. 2016**). Filtering of the data was done as follows:
•	removed trips with missing information,
•	removed drifts that were under 2 minutes (indicative of a non-standard drift),
•	removed year 1987 (under sampled),
•	removed reefs with <12 positive records or all positives in one year,
•	removed depths <30m and >160m, depths at which yelloweye were rarely or never encountered,
•	and removed county 85 (no positives).
This filtering improved the percent positive yelloweye from 10% to 14%, but also pinpointed trips with higher probabilities that yelloweye rockfish could be encountered by reducing total trips by almost half (**Table X**). Model selection explored the inclusion of MONTH, DEPTH, COUNTY, and REEF as factors, in addition to YEAR. The final model was YEAR+MONTH+DEPTH+COUNTY (**Table X**). The data generally met the assumptions of the GLM (**Figure X** and **Figure X**). Both bootstrapping and jackknifing estimates of uncertainty were calculated; jackknifing was used for the reference model (**Table X**). The delta-GLM model results were very different from the geometric average of the catch rates; uncertainty was at moderate levels (**Table X** and **Figure X**). The CPFV index show a similar population decline as the dockside index, with the CPFV index having lower levels of uncertainty (**Figure X**).
2.1.2.2.3 Oregon Onboard Observer CPUE, 2001 – 2024
The Oregon Onboard Observer (now Ocean Recreational Fisheries Survey, or ORFS) index was updated from the previous yelloweye rockfish assessment and updated drift-level catch-per-unit-effort data was obtained from ODFW through the end of 2024. The database contains information on catch by species (number of retained and released fish), effort (angler hours), sample depth, and bag limits and other relevant regulations (@monk_documentation_2013).  
The unfiltered data set contained 18,410 drifts. Multiple standardized filters are applied to remove outliers and data unsuitable for an index. These filters are very similar to filters applied in 2017 and include drifts without data needed for CPUE information, long drifts (below 95th quantile), drifts in deeper waters (less than 64fm, 99th quantile), drifts that were targeting primarily mid-water species, and drifts outside of the legal fishing depth (with a five fm buffer). Additionally, years with extreme low sample sizes (<10) were excluded, including 2003, 2016 and 2019. Finally, drifts onboard charters from Port Orford were removed due to small sample size. The final filtered dataset included 6,839 trips with a 6.1% encounter rate for yelloweye rockfish. 
Covariates evaluated included year, month, port, the open depths to fishing (all depths or inside 20/30/40fm), and a 5fm-binned depth of drift covariate. This is in contrast to the 2017 index, which was only able to evaluate a year covariate. The covariates listed above are standard to evaluate for this index in other assessments. Negative binomial models were fit using sdmTMB (version 0.6.0) to the drift-level data (catch with a log offset for adjusted angler hours). A model without the open fishing depths or month was selected as the best fit model by AIC (Table “model selection”). Acceptable diagnostics for the model were achieved (FIGURE – qqplot). The index of abundance in shown in Figure XXX and Table XXXX. A comparison to the ORFS index used in the previous assessment indicates that despite the change in modeling approach and the covariates included, most years overlap between the two indices and similar trends are observed (Figure “ORFS index comparison”). The updated index has reduced within-year variance and a lack of extreme swings in the standardized index value (e.g. 2013).   
2.1.2.2.4 Oregon MRFSS Dockside CPUE, 1982-1999
**Trip-level dockside interview data from MRFSS (Type-3 records) were provided by ODFW. The original data set runs from 1980-2003, with a gap in coverage in years 1989-1991. Filtering of the data was done as follows:
•	removed counties with no or few encounters,
•	removed waves (i.e., a two-month period) with few to no catches,
•	applied the **Stephens-MacCall (2004)** approach of selecting trips with species compositions most likely to have occurred in yelloweye habitat,
•	and removed years 1980 and 1981 (few encounters) and all years after 1999 (due to management changes).
This filtering improved the percent positive yelloweye rockfish from 27% to 74%, and also reduced the number of samples by 80% (**Table X**). No model selection was possible as YEAR was the only factor with positives in every level. The data generally met the assumptions of the GLM (**Figure X** and **Figure X**). Jackknifing estimates of uncertainty were used for the reference model (**Table X**). The delta-GLM model results shows a general decline in yelloweye rockfish over the period, with moderate to high levels of uncertainty **Table X** and **Figure X**).**
2.1.2.2.5 Oregon ORBS Dockside (release only) CPUE, 2004-2024
The Ocean Recreational Boat Survey (ORBS) dockside index for Oregon was updated for this assessment. CPUE, expressed in terms of fish per angler-hour, was calculated by multiplying the number of anglers and the total trip time, minus the boat type-specific travel time. The database contains information on released fish by species (number of angler-reported released fish), effort (angler hours), sample location (port where data were collected), date, bag limits and other relevant regulations, boat type (charter or private), and trip type (e.g., bottom associated fish). 
The unfiltered data set contained 504,128 trips from 2001 - 2024. Since the previous yelloweye assessment, multiple data filters have been standardized, which are very similar to the 2017 assessment, and are applied to ORBS trip-level data to remove outliers and data unsuitable for an index. For this index, the time period was restricted to years when retention of yelloweye rockfish was prohibited, which began on January 1, 2004. There were two differences in the filtering in this updated index. One, the previous index began in 2005, which was determined to be an error in the timing of the implementation of prohibited status for yelloweye. Given that prohibition was in effect on January 1, the year 2004 is included in this updated index. The second difference in filtering is the elimination of the Stephens-MacCall filter in the updated index. This filter has not been used for several assessment cycles, based on a recommendation from NWFSC staff (pers. comm. A. Whitman, ODFW). The final dataset included 133,039 trips (TABLE “percent_pos.csv”) from 2004 – 2024 with an overall encounter rate of 7.4%.
Covariates evaluated included year, month, port, the open depths to fishing (all depths or inside 20/30/40 fm), and boat type. These are the same covariates evaluated in the 2017 ORBS index, apart from the open depths of the fishery. The final model in 2017 included boat type, port and year. Negative binomial models were fit in sdmTMB (Version 0.6.0) to the trip-level data (catch with a log offset for adjusted angler hours). The final model selected includes year, month, port, boat type and open fishery depths, which was the best fit model by AIC in this series (TABLE “model_selection.csv”). Acceptable diagnostics for the model were achieved (FIGURE – qqplot). The index of abundance in shown in Figure XXX and Table XXXX. ODFW no longer maintains the deltaGLM code that was used to develop the 2017 index and so the index was updated to use the currently accepted modeling approach for PFMC groundfish assessments (sdmTMB). To bridge this change, the 2017 model index structure was applied to the current dataset using sdmTMB and compared to the deltaGLM index used in the 2017 assessment and the current recommended updated index in Figure XX (“ORBS index comparison”). There are some differences observed in 2005 – 2009 between the deltaGLM index and the two sdmTMB indices; however, this appears to be largely driven by the updated modeling approach. A comparison to the ORFS index used in the previous assessment indicates that despite the change in modeling approach and the covariates included, most years overlap between the two indices and similar trends are observed (Figure “ORFS index comparison”). The updated index has reduced within-year variance and a lack of extreme swings in the standardized index value (e.g. 2013). 
2.1.2.2.6 Washington Dockside CPUE, 1982-2001
**The WDFW conducted dockside interviews of recreational fishing trips from 1981-2016. These interviews collected information on catch of several species, including yelloweye rockfish, number of anglers fishing, trip type, boat type, port, fishing area , month, day, week, and other details. Only years prior to and including 2001 were considered given management actions after 2001, which significantly changed the reported number of yelloweye rockfish. Filtering of the data was done as follows:
•	retained “bottomfish only” trips,
•	removed trips with no recorded anglers,
•	removed fishing areas and ports with no catches of yelloweye rockfish,
•	retained trips that caught more than 1 of the following groundfishes: brown, canary, copper, China, quillback, and yelloweye rockfishes, kelp greenling, and lingcod,
•	and retained only months May-September (core bottomfishing months).
This filtering improved the percent positive yelloweye rockfish from 3% to 25%, and reduced the number of samples by 92% to select trips most likely to encounter yelloweye rockfish (**Table  X**). Model selection explored the inclusion of MONTH, BOAT TYPE, and PORT as factors, in addition to YEAR. The final model retained all factors (**Table X**). The data generally met the assumptions of the GLM (Figure 39and Figure 40). Bootstrapping estimates of uncertainty were calculated at relatively low levels (Table 20, Figure 41). The delta-GLM model results were very different from the geometric average of the catch rates; uncertainty was at low levels (**Figure X**). 
Fishery-dependent indices for the Oregon-Washington area are dynamic and highly variable, meaning the information content of each is probably fairly low (**Figure X**).**
2.1.3 Fishery-Dependent Biological Compositions
Most biological data for yelloweye rockfish were reported for both sexes combined. Since composition data and estimates of growth parameters for yelloweye rockfish did not indicate sexual dimorphism in growth, length and age frequency distributions were generated by year for females and males combined. Sampling statistics (number of samples and number of individual fish) for each fleet and year were used to create length and frequency distributions, are shown from **Table X** through **Table X**. 
Length composition data from commercial and recreational fisheries were compiled into 2-cm increment length bins, ranging from 10 to 74 cm. Most lengths were reported as fork lengths, but there were some in the recreational fisheries that were reported as total lengths. A sample of **several hundreds of fish** for which both fork and total lengths were taken were analyzed and a linear relationship (R2 = 0.999) was developed to convert total to fork length. 
Due to sparse sampling as a result of regulatory discard requirements, raw length frequencies are calculated as the count of fish within a given size bin. **This has been the case in previous assessments, and preliminary investigation of alternate weighting procedures revealed little sensitivity to this choice**.
The initial input sample sizes for length frequency distributions of yelloweye rockfish fishery-dependent sources were calculated by year as a function of the number of trips (or samples in the case of recreational fleets) and number of fish sampled, following **Stewart and Hamel (2014)**:
 **ADD FUNCTIONS**
This method was developed based on analysis of the input and model-derived effective sample sizes from West Coast groundfish stock assessments. A step-wise linear regression was used to estimate the increase in effective sample size per sample based on fish-per-sample and the maximum effective sample size for large numbers of individual fish.
 
Age composition data from fisheries ranged from age 0 to age 65. Age composition data were compiled as conditional ages at length (CAAL) distributions by fleet and year. The CAAL approach uses an age-length matrix, in which columns correspond to ages and rows to length bins. The distribution of ages in each column then is treated as a separate observation, conditioned on the corresponding length bin (row). The conditional ages-at-length approach has been used in most stock assessments on the West Coast of the United States in the last decade, since it has several advantages over the use of marginal age frequency distributions. Age structures are usually collected from the individuals that have been measured for length. If the standard age compositions are used along with length frequency distributions in the assessment, the information on year class strength may be double-counted since the same fish are contributing to likelihood components that are assumed to be independent. The use of conditional age distributions within each length bin allows avoiding such double-counting. Also, the use of conditional ages at length distributions allows the reliable estimation of growth parameters within the assessment model. The initial sample sizes for conditional ages-at-length data were the actual numbers of fish on which each composition is based.
Biological information was obtained from a variety of sources. These sources are described below by state and fleet. The length compositions constructed from these data are shown in **Figure X** through **Figure X**. The age compositions constructed from these data are shown in **Figure X** through **Figure X**. 
2.1.3.1 California
2.1.3.1.1 Length Compositions
Updated length composition data for California commercial catches (trawl and non-trawl) were available from PacFIN (extracted on April 4, 2025). Trawl length data were collected between 1978 and 2024, while non-trawl length data were available between 1979 and 2002. Trawl length data were also available from WCGOP between 2019 and 2022, while non-trawl length data were available for the period between 2004 and 2023. Updated length composition data for California recreational fishery were obtained from RecFIN (**extracted …**). These data yielded a relatively consistent number of samples between 1980 and 2024. In early periods (prior to 1993), the lengths from recreational fishery were measured as total length (and converted to fork length), and after 1993 as fork length. Updated length compositions from the California On-Board CPFV Observer Sampling Program were available for the years 1987-1999 and 2004-2024. 
2.1.3.1.2 Age Compositions
Age composition data were extremely limited for California fisheries. No yelloweye rockfish age data were available from the Californian trawl fishery. A sample of only six fish was available from the non-trawl fishery for 2005 from the WCGOP and a limited amount of ages (52 fish) was provided by CDFW for the period 1978-1988 (John Budrick, pers. comm.). A limited amount of recently generated age data were provided from recreational fishery by the SWFSC for 1979-1984 (Don Pearson and John Field, pers. comm.) and by the CDFW for years 2009- 2016 (John Budrick, pers. comm.). The latter data set was generated from confiscated yelloweye rockfish collected from recreational catches, when retention for yelloweye rockfish was prohibited. 
2.1.3.2 Oregon
2.1.3.2.1 Length Compositions
Updated length composition data for Oregon trawl and non-trawl commercial fisheries were obtained from PacFIN (extracted on April 4, 2025). Trawl length compositions were available for years 1995-2024 and non-trawl length compositions were available for years 1995-2024. The WCGOP also provided length composition data for 2005-2023 from the trawl fishery and between 2004 and 2023 from the non-trawl fleet. Updated lengths from the recreational fishery were obtained from RecFIN for 1980-2024. These data were collected in the MRFSS and, the Ocean Recreational Boat Survey (ORBS) dockside sampling programs (total lengths were converted to fork lengths when needed), and from the Ocean Recreational Fishery Survey (ORFS, previously the Oregon onboard recreational observer program), which measures fish discarded at sea.
2.1.3.2.2 Age Compositions
Updated age composition data from Oregon commercial fisheries were obtained from PacFIN and included samples from the trawl fishery (1141 fish) collected in 2001-2024 and from the non-trawl fishery (111 fish) for 2008-2024. The WCGOP also had samples for Oregon-Washington states (information not available at the state level) from trawl fisheries collected in 2004-2006 (77 fish) and from the non-trawl fisheries for 2004-2007 (79 fish). Age composition data from Oregon recreational fisheries were obtained from WDFW (who read age structures) for selected years between 1979 and 2012. Early samples from this dataset (in the 1970s and 1980s) were taken by an ODFW biologist in Garibaldi who saw the offshore fishery starting to develop. A limited amount of yelloweye rockfish age data from the recreational fishery, collected between 2009 and 2016 from fish that were illegally landed and confiscated (since no retention is allowed) were provided by ODFW. 
2.1.3.3 Washington
2.1.3.3.1 Length Compositions
Updated length composition data for the Washington trawl and non-trawl commercial fisheries were obtained from PacFIN (extracted on April 4, 2025). Trawl length compositions were available for 1996-2023 and non-trawl for 1980-2024. The WCGOP also provided lengths for 2005-2019 from the trawl fishery and for 2004-2023 from the commercial non-trawl fleet. Yelloweye rockfish lengths from the recreational fishery were obtained from RecFIN for 1981-2024.
2.1.3.3.2 Age Compositions
Age composition data from Washington commercial fisheries were obtained from PacFIN and included samples from the trawl fishery (268 fish) collected between 2002 and 2023 and from the non-trawl fishery (2166 fish) collected between 2001 and 2024. The WCGOP also had samples for Oregon-Washington states (information not available at the state level) from trawl fisheries collected in 2004-2006 (77 fish) and from the non-trawl fisheries for 2004-2007 (79 fish). Ages from recreational fisheries were obtained from WDFW for selected years between 1979 and 2024. These data were collected in the MRFSS and in the WDFW Ocean Sampling Program (OSP) and obtained from RecFIN.
2.1.4 Fishery-Independent Biological Compositions
 2.1.4.1 Length Compositions
Length composition data were available for all three fishery-independent surveys. The length composition data from the previous assessment was used up to 2016. Data from 2017 through 2024 was obtained for NWFSC West Coast Groundfish Bottom Trawl Survey and the Triennial survey were obtained using functions from the **{nwfscSurvey} R package**. The IPHC survey data was provided from WDFW. 
A summary of sampling efforts (number of hauls and number of individual fish) in all surveys is provided in **Table X** and **Table X**. Length composition data were compiled into 33 length bins, ranging from 10 to 74 cm. Year-specific length frequency distributions generated for each survey are shown in **Figure X**.
The initial input sample sizes for the survey length frequency distribution data were calculated as a function of both the number of fish and number of tows (or STLKEY in the case of the IPHC survey) sampled using the method developed by via Stewart’s Method from the **Pacific Ocean Perch assessment**:
**ADD FUNCTIONS**
which precedes the **Stewart and Hamel (2014)** method that is more specific to species types.
2.1.4.2 Age Compositions
Age composition data were available from the NWFSC trawl survey and IPHC surveys through the same sources as the length data. No age data were available from the triennial survey. As in the case of fishery data, age composition data were assembled into 66 age bins, ranging from age 0 to age 65. Year-specific age frequency distributions generated for each survey are shown in **Figure X** and **Figure X**. In the model, age composition data from the surveys were compiled as conditional distributions of ages at length by survey and year. The initial sample sizes for conditional age-at-length data were the actual numbers of fish on which each composition is based.
2.1.5 Biological Parameters and Data
The length-weight relationship used in this assessment is based on data collected in the NWFSC trawl survey obtained from the **{nwfscSurvey} R package**. Length-weight curves were fitted with the sexes combined using the following relationship:
**ADDE FUCNTION**
Where W is individual weight (kg), L is total natural length (cm) and ⍺ and  β are coefficients used as constants.
The parameters derived from this analysis were as follows: ⍺ = 7.183309·10-6, and β  = 3.244801 (**Figure X **(can be found under Rcode > model_params > plots)). We updated parameters used in the 2011 assessment, since many samples used were based on total lengths in addition to those based on fork lengths.
2.1.5.2 Maturity
2.1.5.3 Fecundity
2.1.5.4 Natural Mortality
2.1.5.5 Ageing Error
2.1.6 Environmental or Ecosystem Data --->
