# Management 

## Reference Points

<!-- 1. Unfished spawning stock biomass, summary age biomass, and recruitment, along with unfished spawning stock output.  -->
<!-- 2. Reference points based on B40% for rockfish and round fish and on B25% for flatfish (spawning biomass and/or output, SPR, exploitation rate, equilibrium yield).  -->
<!-- 3.   Reference points based on default SPR proxy (spawning biomass and/or output, SPR, exploitation rate, equilibrium yield).  -->
<!-- 4. Reference points based on MSY (if estimated) (spawning biomass and/or output, SPR, exploitation rate, equilibrium yield).  -->
<!-- 5. Equilibrium yield curve showing various BMSY proxies.   -->

This assessment estimates that the stock of Yelloweye Rockfish off the continental U.S. Pacific Coast is currently at `r round(mod_out$derived_quants$Value[which(mod_out$derived_quants$Label=="Bratio_2024")], 3)*100`% of its unexploited level. This is above the overfished threshold of SB25%, but below the management target of SB40% of unfished spawning biomass. Both areas are above the overfished level of 25%. The assessment estimates that the coastwide spawning output of Yelloweye Rockfish dropped below the SB40% target for the first time in 1986 and below the overfished SB25% threshold in 1993, as a result of intense fishing by commercial and recreational fleets. It continued to decline and reached 14.2% of its unfished output in 2000 (@tbl-ts). The same year, the stock was declared overfished. Since then, the spawning output has slowly increased due to management regulations implemented to foster stock rebuilding.

Reference points for the base model are summarized in @tbl-ref-points-es-2. Unfished spawning stock output for Yelloweye Rockfish was estimated to be `r round(mod_out$derived_quants$Value[which(mod_out$derived_quants$Label=="SSB_Virgin")], 3)` million eggs (95% confidence interval: 999.2-1267.2 million eggs). The stock is declared overfished if the current spawning output is estimated to be below the minimum stock size threshold (MSST) of 25% of unfished level (SB25%). The management target for Yelloweye Rockfish is defined as 40% of the unfished spawning output (SB40%), which is estimated by the model to be 452 million eggs (95% confidence interval: 397-507), which corresponds to an exploitation rate of 0.026. This harvest rate provides an equilibrium yield of 115 mt at SB40% (95% confidence interval: 101-130 mt). The model estimate of maximum sustainable yield (MSY) is 121 mt (95% confidence interval: 106-136 mt). The estimated spawning stock output at MSY is 327 million eggs (95% confidence interval: 287-367 million eggs). The exploitation rate corresponding to the estimated SPRMSY of F36% is 0.036.

This assessment estimates that the 2024 SPR is `r round(mod_out$derived_quants$Value[which(mod_out$derived_quants$Label=="SPRratio_2024")], 3)`. **The SPR used for setting the OFL is 50%, while the SPR-based management fishing mortality target specified in the current rebuilding plan and used to determine the ACL is 76%. Relative exploitation rates (calculated as catch/biomass of age-8 and older fish) are estimated to have been below 1% during the last decade. This assessment estimates that Yelloweye Rockfish was fished beyond the relative SPR ratio (calculated as 1-SPR/1-SPRTarget=0.5) between 1977 and 2000. The equilibrium yield curve is shown in @fig-eq-yield.**

## Harvest Projections and Decision Tables

The base model estimate for 2025 spawning depletion is `r round(mod_out$derived_quants$Value[which(mod_out$derived_quants$Label=="Bratio_2025")], 3)*100`%. The primary axis of uncertainty about this estimate used in the decision table was based on natural mortality. Natural mortality in the assessment model is fixed at the median of the Hamel prior (0.044 y-1), estimated using the maximum age of 123 years. Natural mortality value for high state of nature was calculated to correspond to 97 years of age, which is the 99th percentile of the age data available for the assessment; this value was 0.056 y-1. The natural mortality value for low state of nature was calculated to correspond to 147 years of age, which is the maximum age reported for the Yelloweye Rockfish; this value was 0.037 y-1.

Twelve-year forecasts for each state of nature were calculated for two catch scenarios (@tbl-es-decision-2). One scenario assumes 2025-2026 catches to be 60% of year-specific ACL values, and 2027-2036 catches to be 60% of removals calculated using current rebuilding SPR of 76% applied to the base model. The second catch scenario assumes 2025-2026 removals to be equal to year-specific ACLs, and 2027-2036 catches calculated using current rebuilding SPR of 76% applied to the base model.

## Evaluation of Scientific Uncertainty

The model estimated uncertainty around the 2025 spawning biomass for the model is 𝜎 = `r round(mod_out$derived_quants$StdDev[which(mod_out$derived_quants$Label=="Bratio_2025")], 3)`. The uncertainty around the OFL in 2025 is 𝜎 = `r round(mod_out$derived_quants$StdDev[which(mod_out$derived_quants$Label=="OFLCatch_2025")], 3)`. Each of these are likely underestimates of overall uncertainty due to the necessity to fix several key population dynamics parameters (e.g., steepness, recruitment variance) and also because there is no explicit incorporation of model structural uncertainty (although see the decision table for alternative states of nature).

## Regional management considerations

Yelloweye Rockfish is modeled in two areas (California and Oregon-Washington) in this assessment. Current population status does differ by area and may be valuable information for making management and allocation decisions (@fig-status-area).

## Research and Data Needs

<!-- 1. Describe progress on Research and Data Needs items identified in the most recent previous stock assessment document and associated STAR panel report.  -->
<!-- 2. Describe new research and data needs and specify their priority (high, medium, low).  -->

Please refer to the 2017 benchmark assessment for a detailed list of research and data needs for Yelloweye Rockfish (@gertseva_stock_2017). In addition to those, the following research and recommendations could improve the ability of future stock assessments to determine the status and productivity of the Yelloweye Rockfish population:

-	USE ONLY ONE INDEX FOR OR REC (CHOOSE ORFS?) and refinement of the ORFS index analysis. Choosing orfs over orbs because it’s a longer time period and orfs and orbs sample the same fishery. 
-	Continue using the methods that we developed for the IPHC index (using sdmTMB).
-	In the model structure, consider expanding age bins for the IPHC data to capture the population dynamics of a long-lived species. (max age in model?) (max age in data)?