# Tables

<!-- Introduction -->

```{r, yelloweye_management}
#| label: tbl-yelloweye_management
#| echo: false
#| warning: false
#| tbl-cap: "Recent trend in the overfishing limits (OFL), the acceptable biological catches (ABCs), the annual catch limits (ACLs), and the total dead catch (landings + discards) all in metric tons (mt)."

# used the csv until two area thing sorted in r4ss
#recent_management_table |>
#  dplyr::rename(`Total dead catch (mt)` = `Catch (mt)`) |>
#  gt::gt() |>
#  gt::tab_options(
#    table.font.size = 12,
#    latex.use_longtable = TRUE 
#  ) |>
#  gt::as_latex()

yelloweye_management <- read.csv("tables/yelloweye_management.csv")
yelloweye_management |>
   gt::gt() |>
   cols_label(
    `Year` = "Year",
    `OFL..mt.` = "OFL (mt)",
    `ABC..mt.` = "ABC (mt)",
    `ACL..mt.` = "ACL (mt)",
    `Catch..mt.` = "Catch (mt)"
  ) |>
   tab_options(
     table.font.size = 12,
     latex.use_longtable = TRUE
   ) |>
   as_latex()

```

{{< pagebreak >}}

<!-- ## Data -->

```{r}
#| label: tbl-all_removals
#| echo: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Time series of yelloweye rockfish catches by fleet used in the assessment. Trawl fleets include yelloweye bycatch in foreign POP and in at-sea Pacific hake fisheries. Years 1967 - 1974, 1979, and 2002 - 2004 do not include WA Sport Catch in MT as that information is not available."

cat("\\begin{landscape}\n")

# This table needs to be redone once the WA sport catches are updated
catch_table |> # produced in 002_load_tables.qmd
#catch_table_est_weights |> # uncomment this line to use the catch table with estimated weights from the SS3 output
  gt() |>
 cols_label(
    year = "Year",
    `1` = "CA trawl (mt)",
    `2` = "CA non-trawl (mt)",
    `3` = "CA sport (mt)",
    `4` = "OR-WA trawl (mt)",
    `5` = "OR-WA non-trawl (mt)",
    `6` = "OR sport (mt)",
    `7` = "WA sport (mt)",
    `8` = "WA sport (1000s fish)",
    Total = "Catch (mt)"
  ) |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  as_latex()

cat("\n\\end{landscape}\n")  
```

{{< pagebreak >}}

```{r, yelloweye_percent_pos_ORFS}
#| label: tbl-yelloweye_percent_pos_ORFS
#| echo: false
#| warning: false
#| tbl-cap: "Summary of trips with and without Yelloweye Rockfish from ORFS index"


read.csv("Tables/yelloweye_percent_pos_ORFS.csv") |> 
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

```{r, yelloweye_model_selection_ORFS}
#| label: tbl-yelloweye_model_selection_ORFS
#| echo: false
#| warning: false
#| tbl-cap: "Model selection for top model covariate combinations considered for the ORFS index"


orfs_modselect <- read.csv("Tables/yelloweye_model_selection_ORFS.csv")[1:10, ]
orfs_modselect[orfs_modselect == "Included"] <- "Incl."
orfs_modselect[is.na(orfs_modselect)] <- '-'
orfs_modselect |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

\clearpage

```{r, yelloweye_percent_pos_ORBS}
#| label: tbl-yelloweye_percent_pos_ORBS
#| echo: false
#| warning: false
#| tbl-cap: "Summary of trips with and without Yelloweye Rockfish from ORBS index"


read.csv("Tables/yelloweye_percent_pos_ORBS.csv") |> 
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

```{r, yelloweye_model_selection_ORBS}
#| label: tbl-yelloweye_model_selection_ORBS
#| echo: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Model selection for top model covariate combinations considered for the ORBS index"

cat("\\begin{landscape}\n")

orbs_modselect <- read.csv("Tables/yelloweye_model_selection_ORBS.csv")[1:10, ]
orbs_modselect[orbs_modselect == "Included"] <- "Incl."
orbs_modselect[is.na(orbs_modselect)] <- '-'
orbs_modselect |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()

cat("\n\\end{landscape}\n") 
```

{{< pagebreak >}}

```{r}
#| label: tbl-sampling-effort-triennial
#| echo: false
#| warning: false
#| tbl-cap: "Summary of sampling effort within triennial survey, with total and yelloweye positive hauls summarized by area."

# This data is directly taken from the pdf of the last assessment report
sampling_tri <- data.frame(
  year = c(1980, 1983, 1986, 1989, 1992, 1995, 1998, 2001, 2004, 1980, 1983, 1986, 1989, 1992, 1995, 1998, 2001, 2004),
  state = c("CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "OR-WA", "OR-WA", "OR-WA", "OR-WA", "OR-WA", "OR-WA", "OR-WA", "OR-WA", "OR-WA"),
  number.hauls = c(68, 96, 95, 147, 135, 123, 129, 129, 103, 263, 416, 389, 300, 310, 241, 260, 246, 185),
  number.positive = c(1, 1, 2, 7, 2, 1, 0, 0, 3, 13, 26, 27, 30, 25, 7, 14, 15, 9)
)

cols_order <- unlist(lapply(c("CA", "OR-WA"), function(x) paste(x, c("number.hauls", "number.positive"), sep = "_")))

data_wide <- sampling_tri |>
  pivot_wider(names_from = "state", values_from = c(number.hauls, number.positive), names_glue = "{state}_{.value}") |>
  select(all_of(c("year", cols_order)))

data_wide |> 
  gt(sampling_tri, rowname_col = "year") |>
  tab_spanner_delim(
    delim = "_",
    split = "first"
  ) |>
  cols_label_with(
    fn = function(x) gsub("number.hauls", "Number of hauls", x)
  ) |>
  cols_label_with(
    fn = function(x) gsub("number.positive", "Number of positive hauls", x)
  ) |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}

```{r}
#| label: tbl-sampling-effort-nwfsc
#| echo: false
#| warning: false
#| tbl-cap: "Summary of sampling effort within NWFSC trawl survey, with total and yelloweye positive hauls summarized by area."

data_wide <- readRDS(here::here("report", "tables", "tbl-sampling-effort-nwfsc.rds")) |>
  tidyr::pivot_wider(names_from = "area", values_from = c(trawl.count, positive.trawl.count), names_glue = "{area}_{.value}") |>
  mutate(
    across(
      c(CA_trawl.count, ORWA_trawl.count, CA_positive.trawl.count, ORWA_positive.trawl.count),
      ~ replace_na(.x, 0)
    )
  ) |>
  select(year, CA_trawl.count, CA_positive.trawl.count, ORWA_trawl.count, ORWA_positive.trawl.count)

data_wide |> 
  gt(sampling_tri, rowname_col = "year") |>
  tab_spanner_delim(
    delim = "_",
    split = "first"
  ) |>
  cols_label_with(
    fn = function(x) gsub("trawl.count", "Number of hauls", x)
  ) |>
  cols_label_with(
    fn = function(x) gsub("positive.trawl.count", "Number of positive hauls", x)
  ) |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()

```

<!-- ## Model summary -->

```{r}
#| label: tbl-model-config
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) config_cap

config_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

\clearpage

```{r}
#| label: tbl-compweight
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) compweight_cap

compweight_table |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}

```{r}
#| label: tbl-n-param
#| warning: false
#| echo: false
#| tbl-cap: !expr if(eval_tables) parcount_cap

parcount_table |>
  dplyr::filter(Count > 0) |>
  gt() |>
  tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  as_latex()
```

{{< pagebreak >}}

<!-- ## Model Results -->

```{r}
#| label: tbl-pars
#| warning: false
#| echo: false
#| results: "asis"
#| tbl-cap: !expr if(eval_tables) pars_cap

pars_table_fixed <- pars_table |>
  mutate(SD = ifelse(Status == 'fixed', NA, SD))

cat("\\begin{landscape}\n")

pars_table_fixed |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Parameter estimates, estimation phase, parameter bounds, estimation status, estimated standard deviation (SD),prior information [distribution(mean, SD)] used in the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 12) |>
  kableExtra::column_spec(
    #column = 1:9,
    width = "0.5in"
  )

#  gt() |>
#  sub_missing(missing_text = '') |>
#  tab_options(
#    table.font.size = 12,
#    latex.use_longtable = TRUE
#  ) |>
#  as_latex()

cat("\n\\end{landscape}\n")
```

{{< pagebreak >}}

```{r, results = "asis"}
#| label: tbl-ts
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) time_series_cap 
#| tbl-pos: H

time_series_table |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Time series of population estimates from the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8) |>
  kableExtra::column_spec(
    column = 1:9,
    width = "0.5in"
  )
```

{{< pagebreak >}}


```{r}
#| label: tbl-sensitivities-like-indices
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (indices)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
indices <- read.csv(here::here("report", "figures", "sensitivities", "indices_table.csv"))
#comps <- read.csv(here::here("report", "figures", "sensitivities", "comp_data_table.csv"))

#indices_and_comps <- inner_join(indices, comps, by = c("Label", "Base"))
#names(indices) <- gsub("X..", "", names(indices))

names(indices) <- c("Label","Base","- CA REC","- OR REC","- WA REC","- CA CPFV","- ORFS","- Triennial","- WCGBTS","- IPHC","No indices")

table_sens(indices)

cat("\n\\end{landscape}\n") 
```

{{< pagebreak >}}

```{r}
#| label: tbl-sensitivities-like-comps-len
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (length compositional data)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
#indices <- read.csv(here::here("report", "figures", "sensitivities", "indices_table.csv"))
len_comps <- read.csv(here::here("report", "figures", "sensitivities", "length_comps_table.csv"))

#indices_and_comps <- inner_join(indices, comps, by = c("Label", "Base"))
#names(comps) <- gsub("X..", "", names(comps))

names(len_comps) <-c("Label","Base","- CA TWL","- CA NONTWL","- CA REC","- ORWA TWL","- ORWA NONTWL","- OR REC","- WA REC","- CA CPFV","- ORFS","- Triennial","- WCGBTS","- IPHC","No length comps")

table_sens(len_comps)

cat("\n\\end{landscape}\n") 
```

{{< pagebreak >}}

```{r}
#| label: tbl-sensitivities-like-comps-age
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (age compositional data)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
age_comps <- read.csv(here::here("report", "figures", "sensitivities", "age_comps_table.csv"))

names(age_comps) <-c("Label","Base","- CA NONTWL","- CA REC","- ORWA TWL","- ORWA NONTWL","- OR REC","- WA REC","- WCGBTS","- IPHC","No age comps","McAllister & Ianelli")

table_sens(age_comps)

cat("\n\\end{landscape}\n") 
```

{{< pagebreak >}}

```{r}
#| label: tbl-sensitivities-model-specs
#| echo: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to model parameters and specifications."

cat("\\begin{landscape}\n")

modeling <- read.csv(here::here("report", "figures", "sensitivities", "modeling_table.csv"))
#names(modeling) <- gsub("X", "", names(modeling))
names(modeling) <- c("Label","Base","Est. M", "Est. steepness","2017 LW relationship")

table_sens(modeling)

cat("\n\\end{landscape}\n") 
```

{{< pagebreak >}}

```{r, tbl-ref-points-es-2, results = "asis"}
#| label: tbl-ref-points-es-2
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) reference_points_cap 
#| tbl-pos: H

reference_points_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(2:4, 7, 10, 12, 15, 17, 20),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 2:4,
    rows = 1,
    decimals = 1
  ) |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(5, 8, 9, 13:14, 18:19),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>  
  gt::tab_style(
    style = list(
      gt::cell_text(style = "italic")
    ),
    locations = gt::cells_body(
      columns = "Reference Point",
      rows = dplyr::starts_with("Reference")
    )
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::as_latex()

```

<!-- ## Management -->

\pagebreak

```{r, results = "asis"}
#| label: tbl-projections
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) projections_cap 
#| tbl-pos: H

cat("\\begin{landscape}\n")

projections_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = c(2:5, 7:9),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = c(6, 10),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::as_latex()

cat("\n\\end{landscape}\n")
```

```{r, 2, results = "asis"}
#| label: tbl-es-decision-2
#| warning: false
#| echo: false
#| tbl-cap: "Decision table with 10-year projections. 'Mgmt' refers to the three management scenarios (A) the default harvest control rule $P^* = 0.45$. In each case the 2025 and 2026 catches are fixed at the ACLs which have been set for that year with estimated fleet allocation provided by the GMT. The alternative states of nature ('Low', 'Base', and 'High' as discussed in the text) are provided in the columns, with Spawning Output ('Spawn', in millions of eggs) and Fraction of unfished spawning output ('Frac') provided for each state."
#| tbl-pos: H
 table_decision(
   list(mod_low_A, mod_base_A, mod_high_A)
 )

```

\pagebreak
