---
title: "diagnostics"
output: html_document
date: "2025-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("remotes")
#remotes::install_github("pfmc-assessments/nwfscDiag")
library(nwfscDiag)
library(r4ss)
library(parallelly)
library(future)

# Set directory and pull in best model

directory <- here::here("model","2025_base_model")
base_model_name <- "updated_alldata_tunecomps_fitbias_ctl_tunecomps_start_20250427"

# Identify the exe location so that the model settings can grab it for running the profiles.
get_ss3_exe(dir = here::here("model", "2025_base_model"))
exe_loc <- here::here(directory, 'ss3.exe')
```

#### Profile Info ####

```{r}
# Specify parameters to profile over along with the parameter range and step size:

### Questions about how the heck we determine these numbers from the control file?

profile_info <- get_settings_profile(
  parameters =  c("NatM_break_1_Fem_GP_1", "SR_BH_steep", "SR_LN(R0)"),
  low =  c(0.4, 0.25, 4.5),
  high = c(0.4, 1.0, 6),
  step_size = c(0.005, 0.05, 0.15),
  param_space = c('multiplier', 'real', 'real')
  )


# profile_info <- get_settings_profile(
#   parameters =  c("NatM_break_1_Fem_GP_1"),
#   low =  c(0.4),
#   high = c(0.4),
#   step_size = c(0.005),
#   param_space = c('multiplier')
#   )
# model_settings <- get_settings(
#   settings = list(
#     base_name = base_model_name,
#       run = c("profile"),
#       profile_details = profile_info )
#     )
# run_diagnostics(mydir = directory, model_settings = model_settings)
```

#### MCMC ####

```{r}
# path <- here::here("model", "MJ_last_run_updated_alldata_tunecomps_fitbias_ctl_start_20250416")
# 
# run_mcmc_diagnostics(
#   dir_wd = path,
#   model = "ss3",
#   extension = ".exe",
#   iter = 10,
#   chains = 2,
#   interactive = FALSE,
#   verbose = TRUE
# )

```

### Compare Model Catch to GEMM catch estimates###

```{r}
# replist <- r4ss::SS_output(path)
# compare_catch <- compare_model_gemm_catch(
#   replist = replist,
#   common_name = "yelloweye rockfish"
# )

```

#### Profile and Jitter and Retrospective in Parallel ####

```{r}

### usepar = FALSE
# THIS IS DEFAULT

#install.packages("parallelly")
#install.packages("future")

ncores <- parallelly::availableCores(omit = 1)
future::plan(future::multisession, workers = ncores)

# YOU CAN USE THIS IN PARALLEL
model_settings <- get_settings(
  settings = list(
    base_name = base_model_name,
    run = c("profile", "jitter", "retro"),
    exe = exe_loc,

    # Profile Settings
    profile_details = profile_info,
    
    # Jitter Settings
    extras = "-nohess",
    Njitter = 50,
    jitter_fraction = 0.10,
    jitter_init_values_src = NULL,
    
    # Retrospective Settings
    newsubdir = "retro",
    retro_yrs = -1:-5,
    
    # Plot target lines
    btarg = NULL,
    minbthresh = NULL)
)

run_diagnostics(mydir = directory, model_settings = model_settings)

future::plan(future::sequential)

```

### Rerun selected values for a profile ###
Do this if some done converge?

```{r}
#base model datafile
# dat <- here::here("model", "MJ_last_run_updated_alldata_tunecomps_fitbias_ctl_start_20250416", "yelloweye_data")
# 
# rerun_profile_vals(
#   mydir = path,
#   model_settings = model_settings, # make sure this is ther correct model settings
#   para_name = "SR_LN(R0)",
#   run_num = c(6,4,3,2), # the runs that didnt converge?
#   data_file_nm = dat
# )

```





